version: '3.0'
services:
  chronicle-consumer-rmq:
    build: ./chronicle-consumer-rmq
    image: chronicle-consumer-rmq
    container_name: chronicle-consumer-rmq
  chronicle-receiver:
    build: ./chronicle-receiver
    image: chronicle
    volumes:
      - $HOME/.chronicle:/opt/data
      - ./chronicle-receiver/config:/opt/config
    environment:
      - DATA_DIR=./data
      - CONFIG_DIR=./config